### ISSUE TITLE
Create Telugu lexicon repository

### ISSUE THREAD

**Issue by damooo** [indic-dict/stardict-telugu#11]
namaste
Can you create a telugu lexicon repository , so that , it will be one place for all telugu texts, like andhra mahabharata, so many shatakas, annamayya, raamadas, tyaagaraaj keertanaas, And so molla ramayana, dicts, research books,encyclopedias published by kaandukuuri vireshalingam and so on . so much of important literature. and if they are at one place with all corrections made, they can be used for any purpose, like creating websites, creating offline dicts, creating searchable pdfs, and so on. so if you create repo, i will start uploading all major works one by one.. : )

**Comment by vvasuki** [comment]
namaste dAmodara - Since we need to be mindful of github repository size limits and such, it is best to have multiple telugu repositories (one for stardict, one for zimfiles etc..), and then provide links to it all in one place - I suggest you creating a sites.google.com page for that. (an example from sanskrit - https://sites.google.com/site/samskrtamsfo ). How about that?

**Comment by damooo** [comment]
hm. that is only,, for stardict , zims,, already repos are there.. that is good. what i mentioned is a seperate repo to handle and create raw content ,like sanskrit lexicon. from that content if we create dicts, they will be in stardict repo only. but only asking a seperate repo for raw text files for corrections etc. not wanting to merge all. again i think my english is bad : )

**Comment by vvasuki** [comment]
Ok! - here you go - https://github.com/sanskrit-coders/telugu-texts .

**Comment by damooo** [comment]
thanks!!
