### ISSUE TITLE
hrasva maatra-s wrong in devanAgarI headwords in telugu

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-telugu#2]
Consider the following line:
కొలము|कोलमु
कोलमु  is wrong. Because को is koo (dIrgha), not कॊ (hrasva). You should use the latter.

Same with the e maatraa - कॆ is hrasva, के is dIrgha.

Reason for this confusion is that ordinary devanAgarI used for hindI / sanskrit etc does not have the hrasva mAtrA for ए and ओ. But its extensions for representing southern sounds do - ऎ, ऒ

**Comment by damooo** [comment]
ॐ  K, till now i don't know about those letters existed in devanagari!! , so now trying to add. but can you give me one information, that does keyboards have those letters?? so that i just want to give these hrasva matras in description only, so that they can know and differentiate sound. and in headwords keep normal , as for searching purpose they will use only normal letters... And cannot input these letters easily...

**Comment by vvasuki** [comment]
Dear damoo, I think it it better to correct it everywhere. If keyboards don't have hrasva mAtra (I expect that many dont) - they can always search with english (just use e for hrasva, E for dIrgha, o for hrasva, O for dIrgha).

**Comment by damooo** [comment]
ॐ । Done , added hrasva matras as seperate head word in head line, and edited in description, where ever case occur.

**Comment by vvasuki** [comment]
అరుపుకొను|अरुपुकोनु|arupukonu|अरुपुकॊनु <-- I see that you've retained the dIrgha rendering too. That's a reasonable decision.

सुकृतम्!
