### ISSUE TITLE
Add headwords without the prathamA vibhakti-pratyaya

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-telugu#3]
Consider కొలము|कोलमु|kolamu. The root (prAtipadika) of this prathamA vibhakti ekavachana form is kola కొల. People in other languages often look up for the root, not the prathamA vibhakti form - so it would be useful to include the root among the headwords in various alphabets.

In this case, we would want:
కొలము|कॊलमु|kolamu|కొల|कॊल|kola

Similarly: జడను|जडनु|jaDanu etc..

**Comment by damooo** [comment]
actually, in telugu du, mu, vu, lu (డు,ము,వు,లు) (डु,मु,वु,लु) are pratyayas for pradhama vibhakti. so it is most common to have 'du' prayaya after root word. like raamudu for raama, anjanudu for anjana , garududu for garuda, like so on... So for du prayaya root word is given now. example as fallows..
  గరుడుడు|గరుడి|గరుత్మంతుడు|గరుటామంతుడు|గరుటాలమంతుడు|गरुडुडु|garuDuDu|garuDa|गरुड|గరుడ
for garududu word, garuda is also added in three languages. So major issue resolved.

coming to pratyaya 'mu', though it is prathama, more than 90% of words having mu at end or original words rather than appending pratyaya. there mu is just part of word, not pratyaya. so for now 'mu' pratyaya is mannually editable only, and not much important, jadanu alsooriginal word, but derived from jada, instead of appending pratyaya.

**Comment by vvasuki** [comment]
Ok, thanks for the update. Follow up questions:
- What about vu and lu?
- So, jaDanuDu vastaaru is a legal sentence?
- Are you sure that according to telugu grammar, the root of kolamu, without the prathama vibhakti suffix mu is not kola? And that it is not the same with other *mu words? Irrespective of what the answer to the previous question is (as far as telugu grammar is concerned), if for most of the *mu words, the root without the mu suffix comes from another language ( say sanskrit), that root should be added - since it benefits users to see the relationship.

**Comment by damooo** [comment]
ॐ । 
1. vu ,, and lu are to minor accurances as pratyaya,, and they are not pratyayas for words from other languages. lu is pratyaya for plural words, like kaayalu is plural of kaaya(fruit). But in Major cases they are part of word, like kaalu means leg. a primary word. but kaa is meaning less, and also not from other languages. major cases are it is part of word.
2.Yup , it is legal. that's why where ever 'uDu' accur  i replaced with 'a' to remove Du pratyaya. like raama for raamuDu. like so. even though 'Du' is pratyaya, in major cases it comes as pratyaya with 'u' sound before too, so 'uDu' occurs means pratyaya. but 'Du' is not always. like vaaDu, means he. vaa, does means nothing... ( though etymologically related).

3.No, kola IS root word for kolamu. that is correct only. but not in all major cases. like paamu means snake, but paa means drink.. like that. telugu is mostly derrived from sanskrit, that's why term sanskrutaandhra came up. each and every sanskrit noun and kriyas are completely valid in telugu, and also adopted into masses with pratyayas added so that it fits into 'ajanta' philosophy. 
- for correlation, they see in only description . in description, all derrived words are mentioned with language, and how it transformed from other language, etc described even with sandhis.. So it is already providing not only base words, but description on how it evolved. there are codes in description if you see, like Skt, Tel, H, Tam,Drav,Port,Vik,Eng, and so on... examples are ....
  [Tadbava form of Skt.  అప్సర.]
  [from Skt. మత్సరము.] , [Tel. fr. ఆ+చోటు.] , [Skt. from అగ్రము.] ,[Skt. from అతిథి], and so on... thesse are there for EVERY word. 
- if in search word you want to add, mu removed, i will add mu removed word too, but so many words will be meaning less, don't know it is fine or not.actually when searched for word they will get those results too even mu is not removed. where as in case of du you will not get, due to addition of'u' . like if search for raama, then search results will be raama, and any words contain raama at first, like raamayya, but not raamudu. so 'du' is problem, and solved. for mu no problem i think, like if u search for agra then it gives agramu too in results to click, as it contains whole search word.

**Comment by vvasuki** [comment]
Very good points - thanks for clarifying. I'll consider this resolved, will follow up in [this issue](https://github.com/sanskrit-coders/stardict-telugu/issues/5) about a child idea.
